server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    discovery:
      enabled: true

  main:
    web-application-type: servlet

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

