server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/ecommerce-product-db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: product-service

eureka:
  client:
    service-url:
      default-zone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true
